config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :families, only: %i[index show new create destroy edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true, length: { minimum: 3 }
  validates :last_name, presence: true, length: { minimum: 3 }
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
  has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true, length: { minimum: 3 }
  validates :last_name, presence:  true, length: { minimum: 3 }
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  has_many :families
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_user, only: %i[index show new create edit update destroy]
  before_action :set_family, only: %i[show edit update destroy]

  def index
    @families = Family.all
  end

  def show
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)
    @family.user = current_user
    if @family.save
      redirect_to families_path(@family)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @family.update(family_params)
    redirect_to family_path(@family)
  end

  def destroy
    @family.destroy
    redirect_to families_path
  end

  private

  def family_params
    params.require(:family).permit(:first_name, :last_name, :age, :avatar)
  end

  def set_user
    @user = current_user
  end

  def set_family
    @family = Family.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/families/index.html.erb
<h1> This is Families index page </h1>

app/views/families/new.html.erb
<h1> Add a new family member </h1>
  <%= simple_form_for(@family) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :age %>
  <%= f.button :submit %>
  <% end %>

app/views/families/show.html.erb
<h1> This is families show page </h1>
<%= @family.first_name %>
<%= @family.last_name %>
<%= @family.age %>
<%= link_to "Edit", edit_family_path(@family) %>
<%= link_to "Back", families_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeCare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>